id: I8B49E87B
initial_creation_type: ebook
source_metadata:
  id: RDI-SK-03
  title: ལག་ལེན་སུམ་སྦྲེལ་གྱི་གདམས་པ་གཅེས་བཏུས།
  author: མཛད་པ་པོ། མཁན་པོ་དྲི་མེད་བློ་གྲོས།, མཛད་པ་པོ། མཁན་པོ་རིན་ཆེན་དར་རྒྱས།, མཛད་པ་པོ།
    སངས་རྒྱས།, མཛད་པ་པོ། ཞྭ་དམར་ལྔ་པ་དཀོན་མཆོག་ཡན་ལག, མཛད་པ་པོ། ཚེ་དབང་ཀུན་ཁྱབ།, མཛད་པ་པོ།
    འཇམ་མགོན་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོ།, མཛད་པ་པོ། འཇམ་དབྱངས་མཁྱེན་བརྩེ་དབང་པོ།, མཛད་པ་པོ།
    བན་རྒན་བསྟན་འཛིན་རྣམ་དག
  authors: &id001
  - མཛད་པ་པོ། མཁན་པོ་དྲི་མེད་བློ་གྲོས།
  - མཛད་པ་པོ། མཁན་པོ་རིན་ཆེན་དར་རྒྱས།
  - མཛད་པ་པོ། སངས་རྒྱས།
  - མཛད་པ་པོ། ཞྭ་དམར་ལྔ་པ་དཀོན་མཆོག་ཡན་ལག
  - མཛད་པ་པོ། ཚེ་དབང་ཀུན་ཁྱབ།
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་ཡོན་ཏན་རྒྱ་མཚོ།
  - མཛད་པ་པོ། འཇམ་དབྱངས་མཁྱེན་བརྩེ་དབང་པོ།
  - མཛད་པ་པོ། བན་རྒན་བསྟན་འཛིན་རྣམ་དག
  sku: RDI-SK-03
  cover: RDI-SK-03.jpeg
  volume: {}
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: ལག་ལེན་སུམ་སྦྲེལ་གྱི་གདམས་པ་གཅེས་བཏུས།
  authors: *id001
  sku: RDI-SK-03
  cover: RDI-SK-03.jpeg
layers:
- Author
- BookNumber
- BookTitle
- Chapter
- Citation
- Commentary
- Footnote
- Sabche
- SubTitle
- Tsawa
- Yigchung
